### ISSUE TITLE
Issue when voting for a proposal

### ISSUE THREAD

**Issue by JoPark20** [X9Developers/hydra-governance#3]
A user voted in favour of a proposal.
The tx hash: 0x9caf1f23c0fd218c9b3489b6baf7cd6b365fddc9525c1dc85b02cd30fdd7959c

Basically says there is "error, anomaly in the contract code".

See Screenshots for more info.  ![unknown.png](https://user-images.githubusercontent.com/43677783/138485578-8d11aea4-3579-499d-8599-2a84fd85ddf6.png)
![unknown.png](https://user-images.githubusercontent.com/43677783/138485591-772c5813-4f3d-490d-ad9c-963dc48e7de0.png)

**Comment by sakalsa** [comment]
What are you planning for the approximate date?

**Comment by AlexITC** [comment]
Unfortunately, there is no ETA defined yet, most of the application is being updated.

**Comment by AlexITC** [comment]
@sakalsa the app/contract was re-written, please wait for instructions to test it again.

Thanks!

**Comment by sakalsa** [comment]
Ok thanks i am waiting impatiently for use. Good luck.
